/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package popstar;

import GameLogic.GameSolver;
import java.io.PrintStream;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author wssccc
 */
class GUIPrintStream extends PrintStream {

    String bufText = "";
    JTextArea text;

    public GUIPrintStream(JTextArea out) {
        super(System.out);
        this.text = out;
    }

    @Override
    public void write(byte[] buf, int off, int len) {
        super.write(buf, off, len);
        String str = new String(buf, off, len);
        bufText = bufText + str;
        text.setText(bufText);
        text.setSelectionStart(bufText.length());
    }
}

public class ResultWindow extends javax.swing.JFrame {

    /**
     * Creates new form ResultWindow
     */
    GameSolver gsolve;

    public ResultWindow(GameSolver gsolve) {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.gsolve = gsolve;
        System.setOut(new GUIPrintStream(jTextArea1));
        new Thread(gsolve).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("宋体", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        gsolve.running = false;
        this.setVisible(false);

    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
